import type { ConditionFieldDef, ConditionGroup } from "../types";

export const CONDITION_FIELDS: ConditionFieldDef[] = [
  // ── 基础评分 ──
  { key: "quality_score", labelKey: "cfQualityScore", category: "basic", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "timing_score", labelKey: "cfTimingScore", category: "basic", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "stage", labelKey: "cfStage", category: "basic", valueType: "string_list",
    operators: ["in", "not_in"], requiresHistory: false, side: "both" },
  { key: "action", labelKey: "cfAction", category: "basic", valueType: "string_list",
    operators: ["in", "not_in"], requiresHistory: false, side: "both" },

  // ── 子评分 ──
  { key: "trend_score", labelKey: "cfTrendScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "momentum_score", labelKey: "cfMomentumScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "volatility_score", labelKey: "cfVolatilityScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "liquidity_score", labelKey: "cfLiquidityScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "breadth_score", labelKey: "cfBreadthScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "breakout_score", labelKey: "cfBreakoutScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "pullback_score", labelKey: "cfPullbackScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "overheat_penalty", labelKey: "cfOverheatPenalty", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "event_score", labelKey: "cfEventScore", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },

  // ── 技术指标 ──
  { key: "daily_change", labelKey: "cfDailyChange", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "buy" },
  { key: "volume_ratio", labelKey: "cfVolumeRatio", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "buy",
    params: [{ key: "avg_period", labelKey: "cfParamAvgDays", type: "number", default: 20 }] },
  { key: "ma_above", labelKey: "cfMaAbove", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [{ key: "period", labelKey: "cfParamMaDays", type: "number", default: 20 }] },
  { key: "ma_below", labelKey: "cfMaBelow", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [{ key: "period", labelKey: "cfParamMaDays", type: "number", default: 20 }] },
  { key: "breakout_high", labelKey: "cfBreakoutHigh", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [{ key: "lookback", labelKey: "cfParamLookback", type: "number", default: 20 }] },
  { key: "pullback_ma", labelKey: "cfPullbackMa", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [
      { key: "period", labelKey: "cfParamMaDays", type: "number", default: 20 },
      { key: "tolerance_pct", labelKey: "cfParamTolerancePct", type: "number", default: 2 },
    ] },

  { key: "close_price", labelKey: "cfClosePrice", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "turnover_rate", labelKey: "cfTurnoverRate", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "sma", labelKey: "cfSma", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }] },
  { key: "ema", labelKey: "cfEma", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }] },
  { key: "price_vs_ma_pct", labelKey: "cfPriceVsMaPct", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }] },
  { key: "rsi", labelKey: "cfRsi", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 14 }] },
  { key: "macd", labelKey: "cfMacd", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "fast", labelKey: "cfParamFast", type: "number", default: 12 }, { key: "slow", labelKey: "cfParamSlow", type: "number", default: 26 }, { key: "signal", labelKey: "cfParamSignal", type: "number", default: 9 }] },
  { key: "macd_signal", labelKey: "cfMacdSignal", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "fast", labelKey: "cfParamFast", type: "number", default: 12 }, { key: "slow", labelKey: "cfParamSlow", type: "number", default: 26 }, { key: "signal", labelKey: "cfParamSignal", type: "number", default: 9 }] },
  { key: "macd_hist", labelKey: "cfMacdHist", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "fast", labelKey: "cfParamFast", type: "number", default: 12 }, { key: "slow", labelKey: "cfParamSlow", type: "number", default: 26 }, { key: "signal", labelKey: "cfParamSignal", type: "number", default: 9 }] },
  { key: "boll_upper", labelKey: "cfBollUpper", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }, { key: "width", labelKey: "cfParamWidth", type: "number", default: 2 }] },
  { key: "boll_mid", labelKey: "cfBollMid", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }, { key: "width", labelKey: "cfParamWidth", type: "number", default: 2 }] },
  { key: "boll_lower", labelKey: "cfBollLower", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }, { key: "width", labelKey: "cfParamWidth", type: "number", default: 2 }] },
  { key: "atr", labelKey: "cfAtr", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 14 }] },
  { key: "kdj_k", labelKey: "cfKdjK", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 9 }] },
  { key: "kdj_d", labelKey: "cfKdjD", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 9 }] },
  { key: "kdj_j", labelKey: "cfKdjJ", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 9 }] },
  { key: "volume_ma", labelKey: "cfVolumeMa", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", labelKey: "cfParamPeriod", type: "number", default: 20 }] },
  { key: "ma_cross_up", labelKey: "cfMaCrossUp", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "both",
    params: [{ key: "short", labelKey: "cfParamShort", type: "number", default: 5 }, { key: "long", labelKey: "cfParamLong", type: "number", default: 20 }] },
  { key: "ma_cross_down", labelKey: "cfMaCrossDown", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "both",
    params: [{ key: "short", labelKey: "cfParamShort", type: "number", default: 5 }, { key: "long", labelKey: "cfParamLong", type: "number", default: 20 }] },
  { key: "custom_expr", labelKey: "cfCustomExpr", category: "technical", valueType: "boolean",
    operators: ["eq", "neq"], requiresHistory: true, side: "both",
    params: [{ key: "expr", labelKey: "cfParamExpr", type: "text", default: "sma(20) > sma(60) and rsi(14) < 70", placeholder: "cross_over('ma5','ma20') or close > boll_upper(20, 2)" }] },

  // ── 卖出条件 ──
  { key: "stop_loss_pct", labelKey: "cfStopLossPct", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: false, side: "sell",
    params: [{ key: "pct", labelKey: "cfParamStopLossPct", type: "number", default: 8 }] },
  { key: "take_profit_pct", labelKey: "cfTakeProfitPct", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: false, side: "sell",
    params: [{ key: "pct", labelKey: "cfParamTakeProfitPct", type: "number", default: 15 }] },
  { key: "trailing_stop", labelKey: "cfTrailingStop", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "sell",
    params: [{ key: "pct", labelKey: "cfParamDrawdownPct", type: "number", default: 10 }] },
  { key: "breakdown_low", labelKey: "cfBreakdownLow", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "sell",
    params: [{ key: "lookback", labelKey: "cfParamLookback", type: "number", default: 20 }] },
  { key: "score_action", labelKey: "cfScoreAction", category: "sell", valueType: "string_list",
    operators: ["in", "not_in"], requiresHistory: false, side: "sell" },
  { key: "max_hold_days", labelKey: "cfMaxHoldDays", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: false, side: "sell",
    params: [{ key: "days", labelKey: "cfParamDays", type: "number", default: 30 }] },
];

export const OPERATOR_LABELS: Record<string, string> = {
  gt: "cfOpGt", gte: "cfOpGte", lt: "cfOpLt", lte: "cfOpLte",
  eq: "cfOpEq", neq: "cfOpNeq", in: "cfOpIn", not_in: "cfOpNotIn",
};

export const CATEGORY_LABELS: Record<string, string> = {
  basic: "cfCatBasic", sub_score: "cfCatSubScore", technical: "cfCatTechnical", sell: "cfCatSell",
};

export const STAGE_OPTIONS = [
  { labelKey: "cfStageStart", value: "start" },
  { labelKey: "cfStageAccel", value: "accel" },
  { labelKey: "cfStageCooldown", value: "cooldown" },
  { labelKey: "cfStageOverheat", value: "overheat" },
];

export const ACTION_OPTIONS = [
  { labelKey: "cfActionOpen", value: "open" },
  { labelKey: "cfActionHold", value: "hold" },
  { labelKey: "cfActionBuyDip", value: "buy_dip" },
  { labelKey: "cfActionReduce", value: "reduce" },
  { labelKey: "cfActionExit", value: "exit" },
];

export const DEFAULT_BUY_GROUP: ConditionGroup = {
  logic: "AND",
  conditions: [
    { field: "quality_score", operator: "gte", value: 60 },
    { field: "timing_score", operator: "gte", value: 55 },
    { field: "stage", operator: "in", value: ["start", "accel"] },
  ],
};

export const DEFAULT_SELL_GROUP: ConditionGroup = {
  logic: "OR",
  conditions: [
    { field: "take_profit_pct", operator: "eq", value: true, params: { pct: 15 } },
    { field: "stop_loss_pct", operator: "eq", value: true, params: { pct: 8 } },
    { field: "max_hold_days", operator: "eq", value: true, params: { days: 30 } },
  ],
};
