import type { ConditionFieldDef, ConditionGroup } from "../types";

export const CONDITION_FIELDS: ConditionFieldDef[] = [
  // ── 基础评分 ──
  { key: "quality_score", label: "股质分", category: "basic", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "timing_score", label: "时点分", category: "basic", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "stage", label: "阶段", category: "basic", valueType: "string_list",
    operators: ["in", "not_in"], requiresHistory: false, side: "both" },
  { key: "action", label: "动作", category: "basic", valueType: "string_list",
    operators: ["in", "not_in"], requiresHistory: false, side: "both" },

  // ── 子评分 ──
  { key: "trend_score", label: "趋势分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "momentum_score", label: "动量分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "volatility_score", label: "波动分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "liquidity_score", label: "流动性分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "breadth_score", label: "广度分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "breakout_score", label: "突破分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "pullback_score", label: "回踩分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "overheat_penalty", label: "过热惩罚", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "event_score", label: "事件分", category: "sub_score", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },

  // ── 技术指标 ──
  { key: "daily_change", label: "日涨幅", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "buy" },
  { key: "volume_ratio", label: "量比", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "buy",
    params: [{ key: "avg_period", label: "均量天数", type: "number", default: 20 }] },
  { key: "ma_above", label: "价格站上MA", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [{ key: "period", label: "均线天数", type: "number", default: 20 }] },
  { key: "ma_below", label: "价格跌破MA", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [{ key: "period", label: "均线天数", type: "number", default: 20 }] },
  { key: "breakout_high", label: "突破N日新高", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [{ key: "lookback", label: "回看天数", type: "number", default: 20 }] },
  { key: "pullback_ma", label: "回踩MA", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "buy",
    params: [
      { key: "period", label: "均线天数", type: "number", default: 20 },
      { key: "tolerance_pct", label: "容忍%", type: "number", default: 2 },
    ] },

  { key: "close_price", label: "Close", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "turnover_rate", label: "Turnover Rate", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: false, side: "both" },
  { key: "sma", label: "SMA", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { key: "ema", label: "EMA", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { key: "price_vs_ma_pct", label: "Price vs MA", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { key: "rsi", label: "RSI", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 14 }] },
  { key: "macd", label: "MACD DIF", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "fast", label: "Fast", type: "number", default: 12 }, { key: "slow", label: "Slow", type: "number", default: 26 }, { key: "signal", label: "Signal", type: "number", default: 9 }] },
  { key: "macd_signal", label: "MACD DEA", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "fast", label: "Fast", type: "number", default: 12 }, { key: "slow", label: "Slow", type: "number", default: 26 }, { key: "signal", label: "Signal", type: "number", default: 9 }] },
  { key: "macd_hist", label: "MACD Hist", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "fast", label: "Fast", type: "number", default: 12 }, { key: "slow", label: "Slow", type: "number", default: 26 }, { key: "signal", label: "Signal", type: "number", default: 9 }] },
  { key: "boll_upper", label: "BOLL Upper", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }, { key: "width", label: "Width", type: "number", default: 2 }] },
  { key: "boll_mid", label: "BOLL Mid", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }, { key: "width", label: "Width", type: "number", default: 2 }] },
  { key: "boll_lower", label: "BOLL Lower", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }, { key: "width", label: "Width", type: "number", default: 2 }] },
  { key: "atr", label: "ATR", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 14 }] },
  { key: "kdj_k", label: "KDJ-K", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 9 }] },
  { key: "kdj_d", label: "KDJ-D", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 9 }] },
  { key: "kdj_j", label: "KDJ-J", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 9 }] },
  { key: "volume_ma", label: "Volume MA", category: "technical", valueType: "number",
    operators: ["gt", "gte", "lt", "lte"], requiresHistory: true, side: "both",
    params: [{ key: "period", label: "Period", type: "number", default: 20 }] },
  { key: "ma_cross_up", label: "MA Cross Up", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "both",
    params: [{ key: "short", label: "Short", type: "number", default: 5 }, { key: "long", label: "Long", type: "number", default: 20 }] },
  { key: "ma_cross_down", label: "MA Cross Down", category: "technical", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "both",
    params: [{ key: "short", label: "Short", type: "number", default: 5 }, { key: "long", label: "Long", type: "number", default: 20 }] },
  { key: "custom_expr", label: "Custom Formula", category: "technical", valueType: "boolean",
    operators: ["eq", "neq"], requiresHistory: true, side: "both",
    params: [{ key: "expr", label: "Expr", type: "text", default: "sma(20) > sma(60) and rsi(14) < 70", placeholder: "cross_over('ma5','ma20') or close > boll_upper(20, 2)" }] },

  // ── 卖出条件 ──
  { key: "stop_loss_pct", label: "止损", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: false, side: "sell",
    params: [{ key: "pct", label: "止损%", type: "number", default: 8 }] },
  { key: "take_profit_pct", label: "止盈", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: false, side: "sell",
    params: [{ key: "pct", label: "止盈%", type: "number", default: 15 }] },
  { key: "trailing_stop", label: "追踪止损", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "sell",
    params: [{ key: "pct", label: "回撤%", type: "number", default: 10 }] },
  { key: "breakdown_low", label: "跌破N日新低", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: true, side: "sell",
    params: [{ key: "lookback", label: "回看天数", type: "number", default: 20 }] },
  { key: "score_action", label: "评分动作", category: "sell", valueType: "string_list",
    operators: ["in", "not_in"], requiresHistory: false, side: "sell" },
  { key: "max_hold_days", label: "最大持仓天数", category: "sell", valueType: "boolean",
    operators: ["eq"], requiresHistory: false, side: "sell",
    params: [{ key: "days", label: "天数", type: "number", default: 30 }] },
];

export const OPERATOR_LABELS: Record<string, string> = {
  gt: ">", gte: "\u2265", lt: "<", lte: "\u2264",
  eq: "=", neq: "\u2260", in: "包含", not_in: "不包含",
};

export const CATEGORY_LABELS: Record<string, string> = {
  basic: "基础评分", sub_score: "子评分", technical: "技术指标", sell: "卖出条件",
};

export const STAGE_OPTIONS = [
  { label: "启动", value: "start" },
  { label: "加速", value: "accel" },
  { label: "冷却", value: "cooldown" },
  { label: "过热", value: "overheat" },
];

export const ACTION_OPTIONS = [
  { label: "开仓", value: "open" },
  { label: "持有", value: "hold" },
  { label: "低吸", value: "buy_dip" },
  { label: "减仓", value: "reduce" },
  { label: "清仓", value: "exit" },
];

export const DEFAULT_BUY_GROUP: ConditionGroup = {
  logic: "AND",
  conditions: [
    { field: "quality_score", operator: "gte", value: 60 },
    { field: "timing_score", operator: "gte", value: 55 },
    { field: "stage", operator: "in", value: ["start", "accel"] },
  ],
};

export const DEFAULT_SELL_GROUP: ConditionGroup = {
  logic: "OR",
  conditions: [
    { field: "take_profit_pct", operator: "eq", value: true, params: { pct: 15 } },
    { field: "stop_loss_pct", operator: "eq", value: true, params: { pct: 8 } },
    { field: "max_hold_days", operator: "eq", value: true, params: { days: 30 } },
  ],
};